package TicketOrder;
// Generated Oct 30, 2016 10:49:21 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int actId;
     private String username;
     private String password;
     private String name;
     private String tel;
     private String email;

    public Account() {
    }

	
    public Account(int actId, String username, String password, String name, String tel) {
        this.actId = actId;
        this.username = username;
        this.password = password;
        this.name = name;
        this.tel = tel;
    }
    public Account(int actId, String username, String password, String name, String tel, String email) {
       this.actId = actId;
       this.username = username;
       this.password = password;
       this.name = name;
       this.tel = tel;
       this.email = email;
    }
   
    public int getActId() {
        return this.actId;
    }
    
    public void setActId(int actId) {
        this.actId = actId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


