package TicketOrder;
// Generated Oct 30, 2016 10:49:21 PM by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private int paymentId;
     private String nameVisa;
     private String numberVisa;
     private String monthExpired;
     private String yearExpired;
     private String pin;
     private int priceAll;

    public Payment() {
    }

    public Payment(int paymentId, String nameVisa, String numberVisa, String monthExpired, String yearExpired, String pin, int priceAll) {
       this.paymentId = paymentId;
       this.nameVisa = nameVisa;
       this.numberVisa = numberVisa;
       this.monthExpired = monthExpired;
       this.yearExpired = yearExpired;
       this.pin = pin;
       this.priceAll = priceAll;
    }
   
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }
    public String getNameVisa() {
        return this.nameVisa;
    }
    
    public void setNameVisa(String nameVisa) {
        this.nameVisa = nameVisa;
    }
    public String getNumberVisa() {
        return this.numberVisa;
    }
    
    public void setNumberVisa(String numberVisa) {
        this.numberVisa = numberVisa;
    }
    public String getMonthExpired() {
        return this.monthExpired;
    }
    
    public void setMonthExpired(String monthExpired) {
        this.monthExpired = monthExpired;
    }
    public String getYearExpired() {
        return this.yearExpired;
    }
    
    public void setYearExpired(String yearExpired) {
        this.yearExpired = yearExpired;
    }
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }
    public int getPriceAll() {
        return this.priceAll;
    }
    
    public void setPriceAll(int priceAll) {
        this.priceAll = priceAll;
    }




}


