package TicketOrder;
// Generated Oct 30, 2016 10:49:21 PM by Hibernate Tools 4.3.1
/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {

     private int ticketId;
     private int timeId;
     private int actId;
     private String origin;
     private String destination;
     private String dateBuyTicket;
     private int numPsg;
     private int pricePerSeat;
     private int paymentId;

    public Ticket() {
    }

    public Ticket(int ticketId, int timeId, int actId, String origin, String destination, String dateBuyTicket, int numPsg, int pricePerSeat, int paymentId) {
       this.ticketId = ticketId;
       this.timeId = timeId;
       this.actId = actId;
       this.origin = origin;
       this.destination = destination;
       this.dateBuyTicket = dateBuyTicket;
       this.numPsg = numPsg;
       this.pricePerSeat = pricePerSeat;
       this.paymentId = paymentId;
    }
   
    public int getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(int ticketId) {
        this.ticketId = ticketId;
    }
    public int getTimeId() {
        return this.timeId;
    }
    
    public void setTimeId(int timeId) {
        this.timeId = timeId;
    }
    public int getActId() {
        return this.actId;
    }
    
    public void setActId(int actId) {
        this.actId = actId;
    }
    public String getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(String origin) {
        this.origin = origin;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getDateBuyTicket() {
        return this.dateBuyTicket;
    }
    
    public void setDateBuyTicket(String dateBuyTicket) {
        this.dateBuyTicket = dateBuyTicket;
    }
    public int getNumPsg() {
        return this.numPsg;
    }
    
    public void setNumPsg(int numPsg) {
        this.numPsg = numPsg;
    }
    public int getPricePerSeat() {
        return this.pricePerSeat;
    }
    
    public void setPricePerSeat(int pricePerSeat) {
        this.pricePerSeat = pricePerSeat;
    }
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }

}


