package TicketOrder;
// Generated Oct 30, 2016 10:49:21 PM by Hibernate Tools 4.3.1



/**
 * Timetrain generated by hbm2java
 */
public class Timetrain  implements java.io.Serializable {


     private int timeId;
     private int trainId;
     private int price;
     private String provice;
     private String dateTrain;
     private String timeTrain;

    public Timetrain() {
    }

	
    public Timetrain(int timeId, int trainId, int price, String provice) {
        this.timeId = timeId;
        this.trainId = trainId;
        this.price = price;
        this.provice = provice;
    }
    public Timetrain(int timeId, int trainId, int price, String provice, String dateTrain, String timeTrain) {
       this.timeId = timeId;
       this.trainId = trainId;
       this.price = price;
       this.provice = provice;
       this.dateTrain = dateTrain;
       this.timeTrain = timeTrain;
    }
   
    public int getTimeId() {
        return this.timeId;
    }
    
    public void setTimeId(int timeId) {
        this.timeId = timeId;
    }
    public int getTrainId() {
        return this.trainId;
    }
    
    public void setTrainId(int trainId) {
        this.trainId = trainId;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getProvice() {
        return this.provice;
    }
    
    public void setProvice(String provice) {
        this.provice = provice;
    }
    public String getDateTrain() {
        return this.dateTrain;
    }
    
    public void setDateTrain(String dateTrain) {
        this.dateTrain = dateTrain;
    }
    public String getTimeTrain() {
        return this.timeTrain;
    }
    
    public void setTimeTrain(String timeTrain) {
        this.timeTrain = timeTrain;
    }




}


